---
# tasks file for kernel




  - name: Ajustement kernel
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
      reload: yes
      ignoreerrors: yes
    with_items : "{{ mq.kernel }}"
    register: kernel



  - name: ----
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%ADMIN ALL='
      line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s
