---
# https://www.ibm.com/docs/fr/ibm-mq/9.2?topic=linux-configuring-tuning-operating-system
# Ajuster les valeurs si nécessaire en fonction du resultat mqconfig
mq:
  limits:
    -  { name: mqm.*hard.*nofile, value: 'mqm              hard    nofile          10240' }
    -  { name: mqm.*soft.*nofile, value: 'mqm              soft    nofile          10240' }
    -  { name: mqm.*hard.*nproc, value: 'mqm              hard    nproc           4096' }
    -  { name: mqm.*soft.*nproc, value: 'mqm              soft    nproc           4096' }