- name: "installation IBM MQ"
  hosts: mq
  become: yes

  pre_tasks:
    - debug:
        msg: "MQ Install"

  roles : 
  - pid
  - limits
  - kernel
  - users
  - mq92

  post_tasks:
    - debug:
        msg: "MQ Install"
