---

##############################################################################
# Désnstallation packages MQ
##############################################################################

   - name: yum
     yum:
       name: "MQSeries*"
       state: absent

     register: __output_file
   - name: debug
     debug:
       var: __output_file


##############################################################################
# Suppression répertoire de dépôt
##############################################################################

   - name: suppression répertoire  de dépôt
     file:
       path: "{{ mq.dest }}/{{ mq.version }}"
       state: absent
